# Generated by Django 3.1.3 on 2021-12-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.DecimalField(decimal_places=0, max_digits=6)),
                ('place', models.CharField(max_length=250)),
                ('max_temperature', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('min_temperature', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('in_range', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=11)),
                ('datetime', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='WebT.sensor')),
            ],
        ),
    ]
